language: python

python:
    - 2.7
    - 3.4

services:
    - rabbitmq

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install zookeeper
    - export MAJOR_TRAVIS_PYTHON_VERSION=$(python -c "import sys;sys.stdout.write(str(sys.version_info.major))")
    - if [ $MAJOR_TRAVIS_PYTHON_VERSION = "3" ]; then pip wheel cython==0.20.1; fi
    - pip install
      -r requirements/base${MAJOR_TRAVIS_PYTHON_VERSION}.txt
      -r requirements/dev.txt

before_script:
    - export ZOOKEEPER_PATH=/usr/share/java

script:
    - mkdir -p tmp
    - pushd tmp
    - nosetests --with-lymph lymph
    - popd

notifications:
    email: false

