language: python

python:
    - 2.7
    - 3.3
    - 3.4

before_install:
    - pip install cython

install:
    - sudo apt-get install zookeeper
    - pip install -r requirements/base.txt
    - pip install .


before_script:
    - export ZOOKEEPER_PATH=/usr/share/java

script:
    - mkdir -p tmp
    - pushd tmp
    - nosetests --with-iris iris
    - popd

notifications:
    email: false

