language: python

python:
    - 2.7
    - 3.3
# TODO: Waiting for https://github.com/travis-ci/travis-ci/issues/1989
#    - 3.4

before_install:
    - sudo apt-get update -qq
    - pip install cython

install:
    - sudo apt-get install zookeeper
    - pip install --no-index .


before_script:
    - export ZOOKEEPER_PATH=/usr/share/java

script:
    - mkdir -p tmp
    - pushd tmp
    - nosetests --with-iris iris
    - popd

notifications:
    email: false

